### ISSUE TITLE
NEEDS MOAR BUTTS

### ISSUE THREAD

**Issue by xrl** [brethash/raspberium-api#1]
kthx bai

**Comment by brethash** [comment]
If you'd like to contribute to the project, please submit a PR for review!
Merci beaucoup!

**Comment by xrl** [comment]
BUTTS

**Comment by brethash** [comment]
hey @xrl ! 
Just wanted to keep you updated w/r/t the whole `butts` situation. `butts` has recently been undergoing a massive refactor. I hope you'll be pleased with the result!
